[package]
name = "ffmpeg6-swresample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
ffmpeg = { package = "ffmpeg-next", version = "6.0.0" }
