name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -Dwarnings
  FFMPEG_DIR: $HOME/ffmpeg/ffmpeg-n6.0-latest-linux64-lgpl-shared-6.0

jobs:
  fmt-check-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download FFmpeg prebuilt
        run: |
          mkdir $HOME/ffmpeg
          cd $HOME
          ls
          echo "----"
          cd $HOME/ffmpeg
          wget --quiet https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n6.0-latest-linux64-lgpl-shared-6.0.tar.xz
          tar -xJf ffmpeg-n6.0-latest-linux64-lgpl-shared-6.0.tar.xz
          ls ..
          echo "===="
          ls
          cd ffmpeg-n6.0-latest-linux64-lgpl-shared-6.0
          ls

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends clang pkg-config

      - name: "Install Rust stable with clippy and rustfmt"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run format
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy
