name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -Dwarnings
  FFMPEG: ffmpeg-n6.0-latest-linux64-lgpl-shared-6.0

jobs:
  fmt-check-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download FFmpeg prebuilt
        run: |
          mkdir $HOME/ffmpeg
          cd $HOME/ffmpeg
          wget --quiet https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/$FFMPEG.tar.xz
          tar -xJf $FFMPEG.tar.xz
          echo "FFMPEG_DIR=$HOME/ffmpeg/$FFMPEG" >> $GITHUB_ENV

      - name: Show
        run: |
          cd $HOME/ffmpeg
          pwd
          echo "===="
          echo $FFMPEG_DIR
          echo "===="
          ls
          cd ffmpeg-n6.0-latest-linux64-lgpl-shared-6.0/
          pwd
          echo "========1"
          ls ./include/libavutil/av* || true
          echo "========2"
          ls "$HOME/ffmpeg/ffmpeg-n6.0-latest-linux64-lgpl-shared-6.0" || true
          echo "========3"
          echo '- ls $FFMPEG_DIR'
          ls "$FFMPEG_DIR" || true
          echo "========4"
          echo "home =" $HOME
          echo '- ls $FFMPEG_DIR/include/libavutil'
          ls $FFMPEG_DIR/include/libavutil/av* || true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends clang pkg-config

      - name: "Install Rust stable with clippy and rustfmt"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run format
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: |
          echo $FFMPEG_DIR
          export FFMPEG_DIR="$HOME/ffmpeg/$FFMPEG"
          cargo clippy
